kind: Deployment
apiVersion: apps/v1
metadata:
  name: test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test1    
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: nginx3
          image: nginx
    