kind: Pod
apiVersion: v1
metadata:
  name: job
spec:
  containers:
    - name: pod-job
      image: nginx
      command: [sh, -c, for i in 1 2 3 4 5 6 7 8 9 10; do sleep 3; date; done]
  restartPolicy: Never
